- name: Cleanup file on a datastore
  community.vmware.vsphere_file:
    hostname: "{{ physical_esxi_info.esxi_host }}"
    username: "{{ physical_esxi_info.esxi_username }}"
    password: "{{ physical_esxi_info.esxi_password }}"
    validate_certs: false
    datacenter: ha-datacenter
    datastore: "{{ physical_esxi_info.datastore_name }}"
    path: "ISOs/{{ nested_info.name }}.iso"
    state: absent
  delegate_to: localhost